[server]
host = "127.0.0.1"
port = 50051
max_connections = 1000
request_timeout_seconds = 300

[storage]
models_directory = "./models"
max_models = 100
cleanup_interval_seconds = 3600

[training]
max_concurrent_training = 4
default_max_epochs = 10000
default_learning_rate = 0.01
default_desired_error = 0.001

[logging]
level = "info"
format = "json"