[package]
name = "opt-eng"
version = "0.1.0"
edition = "2021"
description = "OPT-ENG - Cell Sleep Mode Forecaster"
authors = ["RAN Intelligence Team"]
license = "Apache-2.0"

[dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"

# Machine Learning and Time Series
ruv-fann = { path = "../../../../ruv-fann" }
prophet = { version = "0.1", optional = true }

# Time series and statistics
chrono = { version = "0.4", features = ["serde"] }
statrs = "0.16"

# Networking and gRPC
tonic = "0.11"
tonic-build = "0.11"
prost = "0.12"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
uuid = { version = "1.0", features = ["serde", "v4"] }

# Configuration
config = "0.13"
toml = "0.8"

# Monitoring and metrics
prometheus = "0.13"
tracing = "0.1"
tracing-subscriber = "0.3"

# Utilities
once_cell = "1.19"
lazy_static = "1.4"
regex = "1.10"
rand = "0.8"

# Time series forecasting
arima = "0.2"
linfa = "0.7"
ndarray = "0.15"

[build-dependencies]
tonic-build = "0.11"

[[bin]]
name = "opt-eng-server"
path = "src/bin/server.rs"

[[bin]]
name = "opt-eng-client"
path = "src/bin/client.rs"